name: Create Video

on:
  repository_dispatch:
    types: [create-video]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download audio and image
        run: |
          mkdir -p tmp
          curl -L "${{ github.event.client_payload.audioUrl }}" -o tmp/audio.mp3
          curl -L "${{ github.event.client_payload.imageUrl }}" -o tmp/image.jpg
      
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      
      - name: Create video
        run: |
          ffmpeg -loop 1 -i tmp/image.jpg -i tmp/audio.mp3 -c:v libx264 -tune stillimage -c:a aac -b:a 192k -shortest "tmp/${{ github.event.client_payload.outputFilename }}.mp4"
          ls -la tmp/
      
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: bigbeardpods
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'tmp'
          DEST_DIR: 'videos'
